# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_addr_wrappers", use_symbols = TRUE, package_name = "addr")

#' @docType package
#' @usage NULL
#' @useDynLib addr, .registration = TRUE
NULL

#' Return list of lists of address tags to R.
#' @param input a character vector of addresses
#' @rdname addr_tag
#' @export
usaddress_tag <- function(input) .Call(wrap__usaddress_tag, input)


# nolint end
